### ISSUE TITLE
Reconnect DRPC client with server

### ISSUE THREAD

**Issue by spacecodewor** [bryk-io/pkg#55]
Hello everyone, I ran into the problem of reconnecting the drpc client with the server, if the server crashes in a panic and recovers, the client via tcp, of course, cannot reach it, except for creating a new client, I did not find a way to solve the problem. Maybe someone has a ready-made reconnect practice in the background?

**Comment by bcessa** [comment]
Hi @spacecodewor, the specific semantics and behavior for the reconnection scenario you mentioned tend to be "application specific". For example, there are a number of possible ways you might wanna/need to handle it:

If the server is down/unreachable and the client is trying to send a new request you can:
- Drop the request and report the issue (via logging, telemetry, etc)
- Queue the request and retry automatically once the server is back again
- Re-route the request to another server
- Treat the issue as transient and irrelevant and simply ignore it (for example if this was merely a `Ping` request)
- Use a "circuit breaker" component to avoid propagating the issue to other services
- ...many others...

Neither of these is particularly right or wrong, the most suitable solution will depend on your specific application requirements. As such, low level libraries only provide the required primitives for you to build the best solution for you and your particular needs.

For example, to handle automatic reconnections you could create a `MonitoredConnection` type that wraps together a [Client](https://github.com/bryk-io/pkg/blob/master/net/drpc/client.go#L21) instance and a [Ticker](https://pkg.go.dev/time#NewTicker) to periodically check if the client has active connections to the server using the [IsActive](https://github.com/bryk-io/pkg/blob/master/net/drpc/client.go#L91) method. If the server is down you can try to start a new client connection.

A simpler approach could be to simply use the `Retry` client middleware included with this module. https://github.com/bryk-io/pkg/blob/master/net/drpc/middleware/client/retry.go#L16 

```
// Retry failed requests up to the `max` number of attempts specified. Retried
// errors will be logged as warnings along with details about the specific
// attempt. Multiple tries introduce an increasingly longer backoff delay to
// account for transient failures on the remote. The specific delay for each
// attempt is calculated (in ms) as: `delay * (factor * attempt_number)`
```

You can find an example of how this client middleware can be used here: https://github.com/bryk-io/pkg/blob/master/net/drpc/server_test.go#L436-L465
