### ISSUE TITLE
Cannot install net/drpc

### ISSUE THREAD

**Issue by AlphaNecron** [bryk-io/pkg#83]
### Describe the bug

`go get go.bryk.io/pkg/net/drpc` doesn't work and make other
 dependencies broken.

![image](https://github.com/bryk-io/pkg/assets/57827456/698fc043-bdbe-4f52-992b-77c6b4928b62)![image](https://github.com/bryk-io/pkg/assets/57827456/741e38a6-8546-4674-acb8-91c9410dbd1d)

### Reproduction

Create a new Go project using GoLand, do `go get go.bryk.io/pkg/net/drpc`.

### System Info

```Shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/necron/.cache/go-build"
GOENV="/home/necron/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/necron/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/necron/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/Dev/iceberg/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2979672715=/tmp/go-build -gno-record-gcc-switches"
```

OS: Arch Linux
Go version 1.20.4
```


### Severity

Blocking all usage of the package

### Additional information

_No response_

**Comment by bcessa** [comment]
Hi @AlphaNecron , this commit https://github.com/bryk-io/pkg/commit/c4050ead584c57a80cf4734eee01ca7499100827 removes the dependencies on private module `go.bryk.io/x`. You should be able to `go get go.bryk.io/pkg` to get the update and build your project without issues.

**Comment by AlphaNecron** [comment]
It works now, thanks.
